---
- hosts: localhost
  connection: local
  become: false
  vars:
    ospool_name: kvmpool
    datapool_name: datapool
    backuppool_name: backuppool

  roles:
    - base
    - hypervisor
    - vm-gaming
