---
- name: install kvm packages
  ansible.builtin.pacman:
    name:
     - libvirt
     - openvswitch
     - qemu-base
     - qemu-hw-usb-host
     - swtpm
     - zfs-dkms
    state: present

- name: create os volumes dataset
  community.general.zfs:
    name: "{{ ospool_name }}/volumes"
    state: present

- name: export os volumes dataset name
  ansible.builtin.set_fact:
    hypervisor_os_volumes_dataset_name: "{{ ospool_name }}/volumes"

- name: create data volumes fileset
  community.general.zfs:
    name: "{{ datapool_name }}/volumes"
    state: present

- name: export data volumes dataset name
  ansible.builtin.set_fact:
    hypervisor_data_volumes_dataset_name: "{{ datapool_name }}/volumes"

- name: create qemu hook file
  ansible.builtin.copy:
    src: libvirt/hooks/qemu
    dest: /etc/libvirt/hooks/qemu
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: create qemu hook script to create snapshots
  ansible.builtin.copy:
    src: scripts/create_snapshot.sh
    dest: /usr/local/bin/create_snapshot.sh
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: create backup script to backup kvm volumes
  ansible.builtin.template:
    src: scripts/backup_kvm_volumes.j2
    dest: /usr/local/bin/backup_kvm_volumes.sh
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: create script to create libvirt usb devices
  ansible.builtin.copy:
    src: scripts/libvirt_create_usbdev.sh
    dest: /usr/local/bin/libvirt_create_usbdev.sh
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: create script to attach usb device to vm
  ansible.builtin.copy:
    src: scripts/libvirt_attach_usbdev_to.sh
    dest: /usr/local/bin/libvirt_attach_usbdev_to.sh
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: create script to attach usb devices to vm
  ansible.builtin.copy:
    src: scripts/libvirt_attach_usbdevs_to.sh
    dest: /usr/local/bin/libvirt_attach_usbdevs_to.sh
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: create script to remove libvirt usb device
  ansible.builtin.copy:
    src: scripts/libvirt_remove_usbdev.sh
    dest: /usr/local/bin/libvirt_remove_usbdev.sh
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: create script to remove libvirt usb device by port
  ansible.builtin.copy:
    src: scripts/libvirt_remove_usbport.sh
    dest: /usr/local/bin/libvirt_remove_usbport.sh
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: create script to detach usb device from vm
  ansible.builtin.copy:
    src: scripts/libvirt_detach_usbdev_from.sh
    dest: /usr/local/bin/libvirt_detach_usbdev_from.sh
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: create script to detach usb devices from vm
  ansible.builtin.copy:
    src: scripts/libvirt_detach_usbdevs_from.sh
    dest: /usr/local/bin/libvirt_detach_usbdevs_from.sh
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

