---
- name: install kvm packages
  ansible.builtin.pacman:
    name:
     - libvirt
     - openvswitch
     - qemu-base
     - qemu-hw-usb-host
     - swtpm
     - zfs-dkms
    state: present

- name: create os volumes dataset
  community.general.zfs:
    name: "{{ ospool_name }}/volumes"
    state: present

- name: export os volumes dataset name
  ansible.builtin.set_fact:
    hypervisor_os_volumes_dataset_name: "{{ ospool_name }}/volumes"

- name: create data volumes fileset
  community.general.zfs:
    name: "{{ datapool_name }}/volumes"
    state: present

- name: export data volumes dataset name
  ansible.builtin.set_fact:
    hypervisor_data_volumes_dataset_name: "{{ datapool_name }}/volumes"

- name: create qemu hook file
  ansible.builtin.copy:
    src: libvirt/hooks/qemu
    dest: /etc/libvirt/hooks/qemu
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

- name: create backup script to backup kvm volumes
  ansible.builtin.template:
    src: scripts/backup_kvm_volumes.j2
    dest: /usr/local/bin/backup_kvm_volumes.sh
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'

