---
- name: enable locales in /etc/locale.gen
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: '^#?en_US.UTF-8 UTF-8'
    line: 'en_US.UTF-8 UTF-8'

- name: Generate locales
  ansible.builtin.command: locale-gen
  changed_when: false

- name: Set /etc/locale.conf
  ansible.builtin.copy:
    dest: /etc/locale.conf
    content: |
      LANG=en_US.UTF-8
      LC_ALL=en_US.UTF-8
    mode: "0644"

- name: install base packages
  ansible.builtin.pacman:
    name: "{{ base_packages }}"
    update_cache: true
    state: present

- name: install ansible-pull service
  ansible.builtin.copy:
    src: systemd/ansible-pull.service
    dest: /etc/systemd/system/ansible-pull.service
    mode: "0644"

- name: install ansible-pull timer
  ansible.builtin.copy:
    src: systemd/ansible-pull.timer
    dest: /etc/systemd/system/ansible-pull.timer 
    mode: "0644"

- meta: flush_handlers

- name: enable ansible-pull timer
  ansible.builtin.systemd:
    name: ansible-pull.timer
    enabled: true
    state: started

